Issue#61
cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp pull request #129
Opened 2020-04-08 18:40 UTC by sedrehman

Tutor calendar appearance updated and tutor can edit their availability right from the calendar. Where dark = available and light =not available. 

use any username but for now test with jcat@buffalo.edu and pass: hello123!!

2020-04-08 22:30 UTC, jechepenuk approved these changes

2020-04-09 05:14 UTC, jechepenuk requested changes
calendar does not load

2020-04-09 15:53 UTC, jechepenuk approved these changes

2020-04-09 15:56 UTC, kesamercy approved these changes

2020-04-10 00:03 UTC, TKTre approved these changes
Looks good!  Updates and keeps well.

2020-04-10 14:20 UTC, merged