Issue#74 button for tutor tocontact student
cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp pull request #159
Opened 2020-04-18 16:01 UTC by kesamercy

check to see if the contact student button appears next to the student appt on the tutor page. 
https://www-student.cse.buffalo.edu/CSE442-542/2020-spring/cse-442i/cse442-semester-project-jalapenocrisp/tutorContent/tutor-appts.php?user_id=22

2020-04-21 02:11 UTC, jechepenuk requested changes
right now it doesnt make sense cause the email isnt autofilled, and the tutor doesnt have access to the students email. If we move it to the student profile it would make sense..

2020-04-21 18:31 UTC, jechepenuk approved these changes

2020-04-22 19:12 UTC, sedrehman approved these changes

2020-04-27 00:58 UTC, TKTre approved these changes
Looks good!

2020-04-28 02:47 UTC, merged