Issue#182 Student Completion Rate
cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp pull request #187
Opened 2020-04-29 20:53 UTC by TKTre

Test at: https://www-student.cse.buffalo.edu/CSE442-542/2020-spring/cse-442i/442TreTesting/privateTesting/cse442-semester-project-jalapenocrisp/ 

For Students:
- Log in and navigate to profile
- Make note of Completion Rate
- Go to the Database(or manually make appts) and edit 'complete' and 'cancel' rows
- Refresh page and ensure Completion Rate populates with accurate values.

2020-05-01 22:50 UTC, sedrehman approved these changes

2020-05-01 22:52 UTC, kesamercy approved these changes

2020-05-03 21:50 UTC, jechepenuk approved these changes

2020-05-03 21:56 UTC, jechepenuk requested changes
i completed 2 appts, but my completion rate stayed 10/10

2020-05-03 22:46 UTC, jechepenuk approved these changes

2020-05-03 22:46 UTC, merged