Issue#174 un bann
cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp pull request #190
Opened 2020-05-03 15:55 UTC by sedrehman

### Acceptance Tests:
 -  As a banned student, attempt to log in , you will be denied, then given a link to "contact us". Where you must click on this link. This will take you a new page where you can submit an appeal. 
 -  Upon submitting an appeal, a message in red will appear if the appeal has been successfully made. 
 - You will receive an email with this appeal message as well as the admins on the site.

Here's link to the site where you test this yourself  - https://www-student.cse.buffalo.edu/CSE442-542/2020-spring/cse-442i/cse442/cse442-semester-project-jalapenocrisp/

Use these credentials -
Username - syedrehm@buffalo.edu
Password - Hello123!

2020-05-03 21:53 UTC, jechepenuk requested changes
your "i changed my mind" button extends out of the box so i would just make that button wider. otherwise it works!

2020-05-04 16:01 UTC, jechepenuk approved these changes

2020-05-04 16:09 UTC, kesamercy approved these changes
It works! Like it :)

2020-05-04 16:15 UTC, TKTre approved these changes
Works as described.  (I experienced some clipping on the appeal page, however.  Doesn't at all detract from the good work you've done, just making note of it)

2020-05-04 16:19 UTC, merged